version: '3.4'

services:
  microservice1:
    image: ${DOCKER_REGISTRY-}microservice1
    build:
      context: .
      dockerfile: MicroService1/Dockerfile
    ports:
       - "5000:5000"
  microservice2:
    image: ${DOCKER_REGISTRY-}microservice2
    build:
      context: .
      dockerfile: MicroService2/Dockerfile
    ports:
       - "5010:5010"
